# Generated by Django 4.0.5 on 2022-06-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_profile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='profile_picture',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='This is my fine Bio', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_link',
            field=models.URLField(max_length=2048),
        ),
    ]
